site_name: "multiversum"
theme:
  name: "material"

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true

nav:
  - Home: index.md
  - API Reference:
      - Universe: "api/universe.md"
      - MultiverseAnalysis: "api/multiverse_analysis.md"
