site_name: "multiversum"
theme:
  name: "material"
  logo: "assets/multiversum_favicon_w.png"
  favicon: "assets/multiversum_favicon.png"
  palette:
    primary: "blue"
    accent: "light blue"
  features:
    - content.code.copy

repo_url: https://github.com/jansim/multiversum/

markdown_extensions:
  - mkdocs-click
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true

nav:
  - Home: index.md
  - Reference:
      - CLI: 'cli.md'
      - Config: "api/config.md"
      - Universe: "api/universe.md"
      - MultiverseAnalysis: "api/multiverse_analysis.md"
  - Examples:
      - "Scikit-Learn (Simple)": "https://github.com/jansim/multiversum/tree/main/examples/scikit-learn--simple"
  - Starter Template: https://github.com/jansim/multiversum-template
