site_name: "multiversum"
theme:
  name: "material"

repo_url: https://github.com/jansim/multiversum/

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true

nav:
  - Home: index.md
  - API Reference:
      - Universe: "api/universe.md"
      - MultiverseAnalysis: "api/multiverse_analysis.md"
  - Examples:
      - "Scikit-Learn (Simple)": "https://github.com/jansim/multiversum/tree/main/examples/scikit-learn--simple"
