[dimensions]
scaler = [
  "StandardScaler",
  "MinMaxScaler",
  "no-scaler"
]
feature_selector = [
  "SelectKBest_5",
  "SelectKBest_10",
  "use-all-features"
]
model = [
  "LogisticRegression",
  "DecisionTree",
  "RandomForest"
]

[constraints]
scaler = [
  { value = "no-scaler", allowed_if = { "feature_selector": "use-all-features" } },
  { value = "MinMaxScaler", forbidden_if = { "feature_selector": "use-all-features" } }
]
