# Generated by multiversum
# Note: This file is only for illustrative purposes and the analysis itself may behave slightly differently.
MULTIVERSUM_OVERRIDE_SETTINGS = {
    "universe_id": "6dffec9eaa199f6f57ab70e40f41be45",
    "dimensions": {
        "x": "B",
        "y": "A"
    },
    "run_no": 1,
    "output_dir": "/home/runner/work/multiversum/multiversum/tests/temp/test_MultiverseAnalysis_noteboook_simple_py",
    "seed": 80539
}

# Output:
# Detected MULTIVERSUM_OVERRIDE_SETTINGS, the settings argument will be ignored.
# Setting seed to 80539 (in: [random, numpy.random]).
# Stopping execution_time clock.
# 

import pandas as pd

from multiversum import Universe

settings = {
    "dimensions": {
        "x": "A",
        "y": "B",
    }
}

universe = Universe(
    settings=settings,
)

# Get the parsed universe settings
dimensions = universe.dimensions

final_data = pd.DataFrame({"value": [ord(dimensions["x"]) + ord(dimensions["y"])]})

universe.save_data(final_data)
