name: Deploy docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[docs]

      - name: Build MkDocs site
        run: mkdocs build --site-dir site

      - name: Upload site artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write  # Needed to deploy to GitHub Pages
      id-token: write  # Needed for OpenID Connect (OIDC) authentication

    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v3
        with:
          name: site
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: site
